### ISSUE TITLE
Support ISO language codes to specify a variant

### ISSUE THREAD

**Issue by Lguyogiro** [ElotlMX/py-elotl#12]
En un futuro podriamos tener varios componentes para la misma macrolengua, uno por cada variante. Propongo que hagamos disponible la elección de variante usando los códigos ISO. Por ejemplo:

```
from elotl.nahuatl.morphology import Analyzer

analyzer = Analyzer(lang_code="nhi")  # o Analyzer(lang_code="nci") etc
```

**Comment by ftyers** [comment]
Estoy de acuero para empezar. Pero igual a un plazo más largo, y especialmente para generación, sería interesante tener soporte para los códigos BCP-47.

**Comment by Lguyogiro** [comment]
> 

:monocle_face: looking into it
